# Generated by Django 5.2.1 on 2025-05-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Product features'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='important_details',
            field=models.TextField(blank=True, help_text="Important details like 'sold separately' items"),
        ),
        migrations.AddField(
            model_name='product',
            name='includes',
            field=models.TextField(blank=True, help_text="What's included in the box"),
        ),
        migrations.AddField(
            model_name='product',
            name='inspiration_content',
            field=models.TextField(blank=True, help_text='Inspiration content and links'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_info',
            field=models.TextField(blank=True, help_text='Technical details and requirements'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_links',
            field=models.TextField(blank=True, help_text='JSON array of YouTube video URLs'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(blank=True, help_text='e.g., main, gallery, technical, lifestyle', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(help_text='e.g., Panel Options, Color, Size', max_length=100)),
                ('variant_value', models.CharField(help_text='e.g., Black, Glass, Mirror', max_length=200)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Price difference from base product', max_digits=10)),
                ('sku_suffix', models.CharField(blank=True, help_text='Additional SKU identifier for this variant', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('required', 'Required for Operation'), ('recommended', 'Recommended'), ('related', 'Related Items'), ('accessory', 'Accessory'), ('replacement', 'Replacement Part')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the relationship')),
                ('quantity_needed', models.IntegerField(default=1, help_text='How many of this item are needed')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Is this item mandatory for operation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='products.product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='products.product')),
            ],
            options={
                'unique_together': {('main_product', 'related_product', 'relationship_type')},
            },
        ),
    ]
