# Generated by Django 4.2.7 on 2025-05-26 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productdocument_productspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedproduct',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_as_main', to='products.product'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='related_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appears_as_related_in', to='products.product'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='relationship_type',
            field=models.CharField(choices=[('required_operation', 'Required for Operation'), ('heater_control', 'Sauna Heater Controls'), ('recommended', 'Recommended'), ('related_item', 'Related Items'), ('accessory', 'Accessory'), ('replacement_part', 'Replacement Part')], max_length=20),
        ),
    ]
