# Generated by Django 4.2.7 on 2025-05-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_relatedproduct_main_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.TextField(blank=True, help_text='Shipping information and requirements'),
        ),
    ]
